# permissions for end users to view redisclusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisclusterbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-operator
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisclusterbackup-viewer-role
rules:
- apiGroups:
  - redis.run
  resources:
  - redisclusterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.run
  resources:
  - redisclusterbackups/status
  verbs:
  - get
