---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - redis.run
  resources:
  - distributedredisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.run
  resources:
  - distributedredisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.run
  resources:
  - distributedredisclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.run
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.run
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - redis.run
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.run
  resources:
  - redisclusterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.run
  resources:
  - redisclusterbackups/finalizers
  verbs:
  - update
- apiGroups:
  - redis.run
  resources:
  - redisclusterbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.run
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.run
  resources:
  - redisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.run
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
